// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace donow.iOS
{
	public partial class DealMakerVC : UIViewController
	{
		public DealMakerVC (IntPtr handle) : base (handle)
		{
		}
	}
}
