// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace donow.iOS
{
	public partial class DealMakerDetailVC : UIViewController
	{
		public DealMakerDetailVC (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			ViewBackgroundTransparent.Hidden = true;
			ViewSendRequestView.Hidden = true;

			ButtonSendRequest.TouchUpInside += (object sender, EventArgs e) =>  {
				ViewBackgroundTransparent.Hidden = false;
				ViewSendRequestView.Hidden = false;
			};
			ButtonOkSendRequestView.TouchUpInside += (object sender, EventArgs e) => {

			};
		}
	}
}
