// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace donow.iOS
{
	public partial class DealMakerAcceptedReferralRequestlVC : UIViewController
	{
		public DealMakerAcceptedReferralRequestlVC (IntPtr handle) : base (handle)
		{
		}
	}
}
