// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using CoreGraphics;

namespace donow.iOS
{
	public partial class InfoPage : UIViewController
	{
		public InfoPage (IntPtr handle) : base (handle)
		{
		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			ScrollViewInfoPage.ContentSize = new CGSize (414.0f, 1362.0f);
		}
	}
}
