// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;
<<<<<<< HEAD
=======
using CoreGraphics;
>>>>>>> origin/master

namespace donow.iOS
{
	public partial class LeadUpdateVC : UIViewController
	{
<<<<<<< HEAD
=======

		public LeadUpdateVC (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			this.ParentViewController.NavigationController.SetNavigationBarHidden (true, false);
			this.NavigationController.SetNavigationBarHidden (false, false);
		}
>>>>>>> origin/master
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

<<<<<<< HEAD
=======
			ScrollViewF2F.ContentSize = new CGSize (414f, 1100f); 
			ViewF2FMeetingDown.Hidden = true;
>>>>>>> origin/master
			IList<string> ListThumbsDownReason = new List<string>
			{
				"Customer Cancelled",
				"No Show",
				"Need to Reschedule"
			};
			IList<string> ListCustomerCategorisation = new List<string>
			{
				"Dreamer",
				"Climber",
				"Purist"
			};
			IList<string> ListNextStep = new List<string>
			{
				"Get Product Info",
				"Purist"
			};

<<<<<<< HEAD
//			ButtonLikeMeeting.ImageForState (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Up White.png");
//			ButtonDisLikeMeeting.ImageForState (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Down White.png");
//			ButtonLikeMeetingInfoHelpful.ImageForState (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Up White.png");
//			ButtonDisLikeMeetingInfoHelpful.ImageForState (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Down White.png");
//			ButtonLikeLeadAdvanced.ImageForState (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Up White.png");
//			ButtonDisLikeLeadAdvanced.ImageForState( (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Down White.png");
//
//			TableViewInteractionDislikeReason.Source = new TableSource (InteractionDislikerReason, this);
=======
			ButtonLikeMeeting.SetImage(UIImage.FromBundle ("Thumbs Up White.png"), UIControlState.Selected);
			ButtonDisLikeMeeting.SetImage(UIImage.FromBundle ("Thumbs Down White.png"), UIControlState.Selected);
			ButtonLikeMeetingInfoHelpful.SetImage(UIImage.FromBundle ("Thumbs Up White.png"), UIControlState.Selected);
			ButtonDisLikeMeetingInfoHelpful.SetImage(UIImage.FromBundle ("Thumbs Down White.png"), UIControlState.Selected);
			ButtonLikeLeadAdvanced.SetImage(UIImage.FromBundle ("Thumbs Up White.png"), UIControlState.Selected);
			ButtonDisLikeLeadAdvanced.SetImage(UIImage.FromBundle ("Thumbs Down White.png"), UIControlState.Selected);

			TableViewInteractionDislikeReason.Hidden = true;

			ButtonMeetingDislikeReasonDropDown.TouchUpInside += (object sender, EventArgs e) => {
				TableViewInteractionDislikeReason.Hidden = false;
			};

			ButtonDisLikeMeeting.TouchUpInside += (object sender, EventArgs e) => {
				ViewF2FMeetingDown.Hidden = false;
			};

			ButtonLikeMeeting.TouchUpInside += (object sender, EventArgs e) => {
				ViewF2FMeetingDown.Hidden = true;
			};

			ButtonMeetingDislikeReasonDropDown.TouchUpInside += (object sender, EventArgs e) => {
			
				TableViewInteractionDislikeReason.Source = new TableSource (ListThumbsDownReason, this);
			};
			
			ButtonCustomerCategorizationDropDown.TouchUpInside += (object sender, EventArgs e) =>  {
				TableViewCustomerCategorization.Source = new TableSource (ListCustomerCategorisation, this);
			};

			ButtonNextStepsDropDown.TouchUpInside += (object sender, EventArgs e) =>  {
				TableViewNextSteps.Source = new TableSource (ListNextStep, this);
			};
>>>>>>> origin/master
		}

		public class TableSource : UITableViewSource {

			IList<string> TableItems;
			string CellIdentifier = "TableCell";

<<<<<<< HEAD
			InteractionLeadUpdateVC interactionLeadUpdateVC;

			public TableSource (IList<string> items, InteractionLeadUpdateVC interactionLeadUpdateVC)
			{
				this.interactionLeadUpdateVC = interactionLeadUpdateVC;
				TableItems = items;
			}

=======
			LeadUpdateVC leadUpdateVC;


			public TableSource (IList<string> items, LeadUpdateVC leadUpdateVC)
			{
				this.leadUpdateVC = leadUpdateVC;
				TableItems = items;
			}


>>>>>>> origin/master
			public override nint RowsInSection (UITableView tableview, nint section)
			{
				return TableItems.Count;
			}

			public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
			{
				UITableViewCell cell = tableView.DequeueReusableCell (CellIdentifier);
				string item = TableItems[indexPath.Row];

				//---- if there are no cells to reuse, create a new one
				if (cell == null)
				{ cell = new UITableViewCell (UITableViewCellStyle.Default, CellIdentifier); }

				cell.TextLabel.Text = item;

				return cell;
			}


			public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
			{

			}

		}

	}
}
<<<<<<< HEAD


=======
>>>>>>> origin/master
