// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;

namespace donow.iOS
{
	public partial class LeadUpdateVC : UIViewController
	{
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			IList<string> ListThumbsDownReason = new List<string>
			{
				"Customer Cancelled",
				"No Show",
				"Need to Reschedule"
			};
			IList<string> ListCustomerCategorisation = new List<string>
			{
				"Dreamer",
				"Climber",
				"Purist"
			};
			IList<string> ListNextStep = new List<string>
			{
				"Get Product Info",
				"Purist"
			};

//			ButtonLikeMeeting.ImageForState (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Up White.png");
//			ButtonDisLikeMeeting.ImageForState (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Down White.png");
//			ButtonLikeMeetingInfoHelpful.ImageForState (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Up White.png");
//			ButtonDisLikeMeetingInfoHelpful.ImageForState (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Down White.png");
//			ButtonLikeLeadAdvanced.ImageForState (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Up White.png");
//			ButtonDisLikeLeadAdvanced.ImageForState( (UIControlState.Selected) = UIImage.FromBundle ("Thumbs Down White.png");
//
//			TableViewInteractionDislikeReason.Source = new TableSource (InteractionDislikerReason, this);
		}

		public class TableSource : UITableViewSource {

			IList<string> TableItems;
			string CellIdentifier = "TableCell";

			InteractionLeadUpdateVC interactionLeadUpdateVC;

			public TableSource (IList<string> items, InteractionLeadUpdateVC interactionLeadUpdateVC)
			{
				this.interactionLeadUpdateVC = interactionLeadUpdateVC;
				TableItems = items;
			}

			public override nint RowsInSection (UITableView tableview, nint section)
			{
				return TableItems.Count;
			}

			public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
			{
				UITableViewCell cell = tableView.DequeueReusableCell (CellIdentifier);
				string item = TableItems[indexPath.Row];

				//---- if there are no cells to reuse, create a new one
				if (cell == null)
				{ cell = new UITableViewCell (UITableViewCellStyle.Default, CellIdentifier); }

				cell.TextLabel.Text = item;

				return cell;
			}


			public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
			{

			}

		}

	}
}


