// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;
using CoreGraphics;
using donow.PCL;

namespace donow.iOS
{
	public partial class LeadUpdateVC : UIViewController
	{

		public LeadUpdateVC (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			this.ParentViewController.NavigationController.SetNavigationBarHidden (true, false);
			this.NavigationController.SetNavigationBarHidden (false, false);
			this.NavigationController.NavigationBar.BarTintColor = UIColor.FromRGB (157, 50, 49);
			this.NavigationController.NavigationBar.TintColor = UIColor.White;

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			ScrollViewF2F.ContentSize = new CGSize (414f, 1350.0f); 
			ViewF2FMeetingDown.Hidden = true;

			IList<string> ListThumbsDownReason = new List<string>
			{
				"Customer Cancelled",
				"No Show",
				"Need to Reschedule"
			};
			IList<string> ListCustomerCategorisation = new List<string>
			{
				"Dreamer",
				"Climber",
				"Purist"
			};
			IList<string> ListSalesStages = new List<string>
			{
				"(1) Acquire Lead",
				"(2) Proposal",
				"(3) Follow Up",
				"(4) Close Sale"
			};
			IList<string> ListNextStep = new List<string>
			{
				"Get Product Info",
				"Purist"
			};

			ButtonLikeMeeting.SetImage(UIImage.FromBundle ("Thumbs Up White.png"), UIControlState.Selected);
			ButtonDisLikeMeeting.SetImage(UIImage.FromBundle ("Thumbs Down White.png"), UIControlState.Selected);
			ButtonLikeMeetingInfoHelpful.SetImage(UIImage.FromBundle ("Thumbs Up White.png"), UIControlState.Selected);
			ButtonDisLikeMeetingInfoHelpful.SetImage(UIImage.FromBundle ("Thumbs Down White.png"), UIControlState.Selected);
			ButtonLikeLeadAdvanced.SetImage(UIImage.FromBundle ("Thumbs Up White.png"), UIControlState.Selected);
			ButtonDisLikeLeadAdvanced.SetImage(UIImage.FromBundle ("Thumbs Down White.png"), UIControlState.Selected);

			TableViewInteractionDislikeReason.Hidden = true;

			TableViewInteractionDislikeReason.Source = new TableSource (ListThumbsDownReason, this);
			ButtonMeetingDislikeReasonDropDown.TouchUpInside += (object sender, EventArgs e) => {
				TableViewInteractionDislikeReason.Hidden = false;
			};

			ButtonDisLikeMeeting.TouchUpInside += (object sender, EventArgs e) => {
				ViewF2FMeetingDown.Hidden = false;
			};

			ButtonLikeMeeting.TouchUpInside += (object sender, EventArgs e) => {
				ViewF2FMeetingDown.Hidden = true;
				TableViewInteractionDislikeReason.Hidden = true;
			};

			TableViewSalesStage.Source = new TableSource (ListSalesStages, this);
			ButtonSaleStageDropDown.TouchUpInside += (object sender, EventArgs e) => {
				TableViewSalesStage.Hidden = false;
			};

			TableViewCustomerCategorization.Source = new TableSource (ListCustomerCategorisation, this);
			ButtonCustomerCategorizationDropDown.TouchUpInside += (object sender, EventArgs e) =>  {
				TableViewCustomerCategorization.Hidden = false;
			};

			TableViewNextSteps.Source = new TableSource (ListNextStep, this);
			ButtonNextStepsDropDown.TouchUpInside += (object sender, EventArgs e) =>  {
				TableViewNextSteps.Hidden = false;
			};

//			LeadsBL leadbl = new LeadsBL();
//			LeadF2FFeedBack leadf2ffeedback = new LeadF2FFeedBack();
//			leadf2ffeedback.LeadID = 1231;
//			leadf2ffeedback.UserID = 1;
//			leadf2ffeedback.ReasonForDown = "Not Ok";
//			leadf2ffeedback.ConfirmMeeting = "UP";
//			leadf2ffeedback.CustomerCategorization = "dadaoene";
//			leadf2ffeedback.MeetingInfoHelpFull = "";
//			leadf2ffeedback.LeadAdvanced = "UP";
//			leadf2ffeedback.NextSteps = "dadaoene";
//			leadf2ffeedback.SalesStage = "Followup";
//			leadbl.SaveLeadF2FFeedBack(leadf2ffeedback);
		}

		public class TableSource : UITableViewSource {

			IList<string> TableItems;
			string CellIdentifier = "TableCell";

			LeadUpdateVC leadUpdateVC;


			public TableSource (IList<string> items, LeadUpdateVC leadUpdateVC)
			{
				this.leadUpdateVC = leadUpdateVC;
				TableItems = items;
			}


			public override nint RowsInSection (UITableView tableview, nint section)
			{
				return TableItems.Count;
			}

			public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
			{
				UITableViewCell cell = tableView.DequeueReusableCell (CellIdentifier);
				string item = TableItems[indexPath.Row];

				//---- if there are no cells to reuse, create a new one
				if (cell == null)
				{ cell = new UITableViewCell (UITableViewCellStyle.Default, CellIdentifier); }

				cell.TextLabel.Text = item;

				return cell;
			}


			public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
			{

			}

		}

	}
}
