// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace donow.iOS
{
	public partial class MyDealMakerDetailVC : UIViewController
	{
		public MyDealMakerDetailVC (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// Navigation
			UIBarButtonItem btn = new UIBarButtonItem ();
			btn.Image = UIImage.FromFile("Navigation Back Icon.png");
			btn.Clicked += (sender , e)=>{
				MyDealMakerVC signUpPage = this.Storyboard.InstantiateViewController ("MyDealMakerVC") as MyDealMakerVC;
				this.NavigationController.PushViewController(signUpPage,true);
			};
			NavigationItem.LeftBarButtonItem = btn;

			ViewBackgroundTransparent.Hidden = true;
			ViewSendRequestView.Hidden = true;

			ViewSendRequestView.Layer.CornerRadius = 10.0f;
			ButtonOkSendRequestView.Layer.CornerRadius = 5.0f;

			ButtonSendRequest.TouchUpInside += (object sender, EventArgs e) =>  {
				ViewBackgroundTransparent.Hidden = false;
				ViewSendRequestView.Hidden = false;
			};
			ButtonOkSendRequestView.TouchUpInside += (object sender, EventArgs e) => {
				ViewBackgroundTransparent.Hidden = true;
				ViewSendRequestView.Hidden = true;
			};


			ButtonSendRequest.Layer.CornerRadius = 8.0f;
			ButtonOkSendRequestView.Layer.CornerRadius = 8.0f;

			ButtonCancel.Layer.BorderWidth = 2.0f;
			ButtonCancel.Layer.BorderColor = UIColor.FromRGB (45, 125, 177).CGColor;
			ButtonCancel.Layer.CornerRadius = 8.0f;

//			ScrollViewDealMakerDetails.ContentSize = new CGSize (414, 633.0f);
		}
	}
}
